version: "4"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xmx4096m"
      - "cluster.max_shards_per_node=6000"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
      - "xpack.security.enrollment.enabled=false"
    networks:
    - efk-idranalysis
    volumes:
    # Elasticsearch database
    - ./volumes/es:/usr/share/elasticsearch/data

  fluentd:
    build:
      context: ./fluentd
      network: host
    networks:
    - efk-idranalysis
    links:
    - "elasticsearch"
    volumes:
    - ./fluentd/conf:/fluentd/etc
    - /uod/idr/versions/idr-analysis-logs-cmbined/:/idranalysis-haproxy-logs/:ro
    - /uod/idr/versions/nginx-logs-combined/prod-merged-agg/:/idr-nginx-logs:ro
    - ./volumes/fluentd/:/fluentd/pos/

  kibana:
    image:  docker.elastic.co/kibana/kibana:8.8.1
    networks:
     efk-idranalysis:
       ipv4_address: "10.11.0.10"

  nginx:
    image: library/nginx:1.24.0
    links:
    - "elasticsearch"
    networks:
    - efk-idranalysis
    ports:
    - "12381:8080"
    volumes:
    # Nginx configuration
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # Nginx basic auth
    - ./nginx/httppasswd:/etc/nginx/httppasswd:ro
    # logs files
    - ./volumes/nginx/log/:/var/log/nginx/

networks:
  efk-idranalysis:
    ipam:
      driver: default
      config:
        - subnet: 10.11.0.0/16
